name: Create a jira ticket for SDOP
description: "Work only for PR comments"
inputs:
  jira_token:
    description: Jira token to create ticket
    required: true
  jira_base_url:
    description: Jira base url
    required: true
  extra_labels:
    description: Extra labels to add to the ticket
    required: false
  test:
    description: Is this execution a test/dry-run
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Create Jira Ticket for SDOP Deployment
      shell: bash
      env:
        JIRA_TOKEN: ${{ inputs.jira_token }}
        JIRA_BASE_URL: ${{ inputs.jira_base_url }}
        TEST: ${{ inputs.test }}
        EXTRA_LABELS: ${{ inputs.extra_labels }}
        SUMMARY: ${{ github.event.head_commit.message }}
        DESCRIPTION: ${{ github.event.head_commit.message }}
        RUN_STARTED_AT: ${{ github.event.workflow_run.run_started_at }}
      run: |
        WHEN_WAS_DEPLOYED=$(date -Iseconds)
        TO_ADD_LABELS=()
        IFS=',' read -ra TO_ADD_LABELS <<< "$EXTRA_LABELS"

        if [ "$TEST" = "true" ]; then
          TO_ADD_LABELS+=("SDOPexclude")
        fi

        for i in "${!TO_ADD_LABELS[@]}"; do
            TO_ADD_LABELS[$i]=$(echo "${TO_ADD_LABELS[$i]}" | xargs)
        done
        LABELS=$(printf '"%s",' "${TO_ADD_LABELS[@]}")
        LABELS="[${LABELS%,}]"
        
        # Calculate difference in minutes
        MINUTES_OF_DEPLOYMENT=$(( ($(date +%s) - $(date -d "$RUN_STARTED_AT" +%s)) / 60 ))

        PAYLOAD=$(cat <<EOF
        {
          "verb": "POST",
          "fields": {
            "issuetype": { "name": "SDOP Deployment" },
            "summary": "$SUMMARY",
            "components": [
              { "name": "1988-Lara AI" }
            ],
            "labels": $LABELS,
            "description": "$DESCRIPTION",
            "customfield_16561": "$WHEN_WAS_DEPLOYED",
            "customfield_19761": "$MINUTES_OF_DEPLOYMENT",
            "customfield_26160": 10,
            "customfield_27260": 1,
            "project": { "id": 40203 }
          }
        }
        EOF
        )

        curl --location "$JIRA_BASE_URL/jira_gateway/create_issue" \
          --header "Authorization: Bearer $JIRA_TOKEN" \
          --header "Content-Type: application/json" \
          --data "$PAYLOAD"
